---
version: "2.0"
services:
  pz-server:
    image: ghcr.io/hrkcz001/pz-akash-server:sha-6251831
    expose:
      - port: 16261
        as: 16261
        proto: udp
        to:
          - global: true
            ip: pz-ip
      - port: 16262
        as: 16262
        proto: udp
        to:
          - global: true
            ip: pz-ip
      - port: 27015
        as: 27015
        proto: tcp
        to:
          - global: true
            ip: pz-ip
      - port: 2222
        as: 2222
        proto: tcp
        to:
          - global: true
            ip: pz-ip
    env:
      - >-
        SSH_PRIVATE_KEY_BASE64=YOUR_BASE64_ENCODED_SSH_PRIVATE_KEY_HERE
      - REPO_URL=git@github.com:hrkcz001/pz-saves.git
      - GIT_USER_NAME=hrkcz001
      - GIT_USER_EMAIL=hrkcz001@gmail.com
      - SSH_PORT=2222
      - SERVER_NAME=vsrania
      - ADMIN_PASSWORD=CHANGE_ME
      - SERVER_MEMORY_MAX=14336m
      - SERVER_MEMORY_MIN=14336m
      - RESTORE_POLL_INTERVAL_SEC=10
      - WAIT_ON_CRASH_SEC=1800
profiles:
  compute:
    pz-server:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 30Gi
  placement:
    pz-placement:
      pricing:
        pz-server:
          denom: uakt
          amount: 100000
deployment:
  pz-server:
    pz-placement:
      profile: pz-server
      count: 1
endpoints:
  pz-ip:
    kind: ip
