version: '3.8'

services:
  pz-server:
    build: .
    container_name: pz-server
    restart: unless-stopped
    environment:
      - SSH_PRIVATE_KEY_BASE64=LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNERFZVcDV6czJGVWh6U05jaXVWd211ejVJb3dXbE5ybUtxbkNYNmRJSUlnZ0FBQUtET3kvZlJ6c3YzCjBRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRERWVXA1enMyRlVoelNOY2l1VndtdXo1SW93V2xOcm1LcW5DWDZkSUlJZ2cKQUFBRUQvT3VVUFZpcFpibXZuRHNFV0RBSDhRNUxUYWxPVUQ0czA0VFJmSG0rVXJzTlZTbm5PellWU0hOSTF5SzVYQ2E3UApraWpCYVUydVlxcWNKZnAwZ2dpQ0FBQUFGbWh5YTJONk1EQXhRSFJvYVhNdFkyOXRjSFYwWlhJQkFnTUVCUVlICi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
      - REPO_URL=git@github.com:hrkcz001/pz-saves.git
      - SAVE_COMMIT_HASH=latest
      - GIT_USER_NAME=hrkcz001
      - GIT_USER_EMAIL=hrkcz001@gmail.com
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
