PVP=true

PVPLogToolChat=true

PVPLogToolFile=true

PauseEmpty=true

DisplayUserName=true

ShowFirstAndLastName=false

UsernameDisguises=false

SafetySystem=false

ShowSafety=false

DefaultPort=16261

UDPPort=16262

#Mods=ModLoadOrderSorter_b42;ModManager;UnifiedCarryWeightFramework;damnlib;67gt500;68firebird;69fordMustang;69fordMustangExtra;70barracuda;70roadRunner;73fordFalcon;73fordFalconPS;73nissanGTR;76chevyKseries;76chryslerNewYorker;77firebird;79camaro;82firebird;82firebirdKITT;82jeepJ10;82jeepJ10t;82porsche911;84buickElectra;84jeepXJ;84merc;85buickLeSabre;85chevyCaprice;85chevyStepVan;85chevyStepVanexpanded;85oldsmobileDelta88;85pontiacParisienne;86chevyCUCV;86fordE150;86fordE150dnd;86fordE150expanded;86fordE150mm;86fordE150pd;87buickRegal;87chevySuburban;87toyotaCorolla;87toyotaMR2;88chevyS10;88toyotaHilux;89dodgeCaravan;89fordBronco;89trooper;89volvo200;90bmwE30;91fordLTD;91fordRanger;91lexusLS400;92amgeneralM998;92amgeneralM998extra;92fordCVPI;92nissanGTR;93chevySuburban;93chevySuburbanExpanded;93fordF350;93fordTaurus;93mustangSSP;95impreza;96lancerEVO;98stagea;99fordCVPI;KI5trailers;CargoTrailer_BubbysVariants;KI5campers;better-auto-mechanics;dustinguished_bolt_cutters;KeepPerkLevel;YAPZLib;SpecLoot;STA_EngineRebuild;VASinked;VB_CommonSense;vehiclepaintsystem;VHSSkillNameInTooltip;VVR;ZeroWeightKeys_B42;TNFPB42;TNFP;VanillaGearExpanded;BetterLockpickingContinued;ChevalDeFriseFix;ChuckleberryFinnAlertSystem;errorMagnifier;Explosives;jiggasGreenfireMod;LTWB42;NWMF1;SlowGasMaskFiltersB42;stihlchainsaw;TEBFP;TNFPDurability;TNFPFirearmsPatch;TNFPFirearmsPatchFirerate;TNFPNameB41Revamped;TNFPNameVFE;TNFPNatoReponse;TNFPNatoReponseBandits;TVFR;KI5RUS;VANGEAEXRUS

DoLuaChecksum=false

Public=false

MaxPlayers=32

PlayerSafehouse=false

AllowDestructionBySledgehammer=true

RCONPort=27015

RCONPassword=Qwerty0123**

Password=1488

SleepAllowed=true

SleepNeeded=false

SteamVAC=false

SpeedLimit=150.0

FastForwardMultiplier=40.0

PerkLogs=true

AllowNonAsciiUsername=true

MouseOverToSeeDisplayName=true

CarEngineAttractionModifier=0.2

PlayerBumpPlayer=true

MapRemotePlayerVisibility=1

BackupsOnStart=false

BackupsOnVersionChange=false

BackupsPeriod=0

DisableScoreboard=true