---
version: "2.0"
services:
  pz-autosave:
    image: ghcr.io/hrkcz001/pz-akash-autosave:latest
    expose:
      - port: 80
        as: 80
        proto: tcp
        to:
          - global: true
    env:
      - >-
        SSH_PRIVATE_KEY_BASE64="<YOUR_BASE64_SSH_KEY>"
      - REPO_URL=git@github.com:hrkcz001/pz-saves.git
      - GIT_USER_NAME=hrkcz001
      - GIT_USER_EMAIL=hrkcz001@gmail.com
      - HTTP_PORT=80
      - BACKUP_INTERVAL_SEC=3600
      - BACKUP_RETENTION_DAYS=7
      - RCON_PASSWORD=Qwerty0123**
      - RCON_PORT=27015
      - AUTOSAVER_POLL_SEC=60
      - SSH_CONNECT_TIMEOUT=10
profiles:
  compute:
    pz-autosave:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 20Gi
  placement:
    pz-placement:
      pricing:
        pz-autosave:
          denom: uakt
          amount: 1000
deployment:
  pz-autosave:
    pz-placement:
      profile: pz-autosave
      count: 1
