---
version: "2.0"
services:
  pz-autosave:
    image: ghcr.io/hrkcz001/pz-akash-autosave:latest
    expose:
      - port: 80
        as: 80
        proto: tcp
        to:
          - global: true
    env:
      - >-
        SSH_PRIVATE_KEY_BASE64="<YOUR_BASE64_SSH_KEY>"
      - REPO_URL=git@github.com:hrkcz001/pz-saves.git
      - GIT_USER_NAME=hrkcz001
      - GIT_USER_EMAIL=hrkcz001@gmail.com
profiles:
  compute:
    pz-autosave:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 50Gi
  placement:
    pz-placement:
      pricing:
        pz-autosave:
          denom: uakt
          amount: 1000
deployment:
  pz-autosave:
    pz-placement:
      profile: pz-autosave
      count: 1
